# Generated by Django 4.0.3 on 2022-04-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_postimage_image_postvideo_postaudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaudio',
            name='audio',
            field=models.FileField(max_length=254, upload_to='post/media/audios'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='post/media/images'),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='video',
            field=models.FileField(max_length=254, upload_to='post/media/videos'),
        ),
    ]
