# Generated by Django 4.0.3 on 2022-05-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
